version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: es01
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
