version: '3.3'
services:
  elastic01:
    env_file: .env
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    container_name: elastic01
    environment:
      - node.name=elastic01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic02
      - cluster.initial_master_nodes=elastic01,elastic02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTIC_NODE01_HEAP} -Xmx${ELASTIC_NODE01_HEAP}"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  elastic02:
    env_file: .env
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    container_name: elastic02
    environment:
      - node.name=elastic02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic01
      - cluster.initial_master_nodes=elastic01,elastic02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTIC_NODE01_HEAP} -Xmx${ELASTIC_NODE01_HEAP}"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.monitoring.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana01:
    env_file: .env
    image: "docker.elastic.co/kibana/kibana:${ELK_VERSION}"
    container_name: kibana01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic01:9200
      - ELASTICSEARCH_HOSTS=["http://elastic01:9200","http://elastic02:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - XPACK_GRAPH_ENABLED=true
      - XPACK_WATCHER_ENABLED=true
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
      - XPACK_MONITORING_KIBANA_COLLECTION_ENABLED=true
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge